const LANGUAGE = 'LANGUAGE';
const UNITS = 'UNITS';
const CITY = 'CITY';
const SET_MAP_TYPE = 'SET_MAP_TYPE';
const COORD = 'COORD';
const DATA = 'DATA';

export  {LANGUAGE, UNITS, CITY, SET_MAP_TYPE, COORD, DATA}